name: '${name}'
version: '${version}'
description: '${description}'
main: '${group}.bukkit.BukkitMain'
load: STARTUP
authors: ['LittleSkin']
website: 'https://littleskin'
softdepend: [ ProtocolLib ]
api-version: 1.13
